apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: crossplane-contrib-function-auto-ready
spec:
  package: 'xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.2.1' #kleber-check
